language: android
dist: precise
sudo: required
jdk:
- oraclejdk8
env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2
android:
  components:
    - tools 
    - platform-tools
    - build-tools-26.0.2
    - tools
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew build
